name: crossplat_objectid
description: Cross-platform BSON ObjectId implementation in Dart
version: 3.0.0
homepage: https://github.com/tejainece/bson_objectid

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.17.2
